package com.mcdev.spazes.util

//const val API_KEY = "jFoYfOJGvoRXhEW2psvODmCdY"
//const val API_SECRET_KEY = "DEN0cpcw4YycAFHWlb5Fw0aFcWmOFKOqiNGcICunjKY2yZXJ2m"
//const val ACCESS_TOKEN = "508658764-LQhk4a94lX9YaJmE6dEO8pUDbGsYjRLLHaCyPhpu"
//const val ACCESS_TOKEN_SECRET = "1H8tOaXb1eBzGth8zaXPjzVTNMlUHtyeP3hKrSSqcXjtZ"
//const val BEARER_TOKEN = "AAAAAAAAAAAAAAAAAAAAAJ9BTgEAAAAA3X86p6qUcjKq34HSUkYLlw3bHDY%3DuJ4RfEclWciQ5l6FrtUvodHj74JyNpsgzgXqOn6I91w9DePIdn"
const val API_KEY = "SzklBX9zOp943lsemx2LsSmGH"
const val API_SECRET_KEY = "OqQX3h91P6sdlGCnwpb8vrMYtFI41UzySSKZkNc0dnUGRGeOwu"
const val ACCESS_TOKEN = ""
const val ACCESS_TOKEN_SECRET = ""
const val BEARER_TOKEN = "AAAAAAAAAAAAAAAAAAAAAEnHZAEAAAAAhIFRBrxhbf%2Fz%2BQFGXT2oN9dJ4QA%3DoH4N81tduqqKhLhwsuKpI5wVW4DxjYTC7g07scKoHP7f7sNdeU"
const val CLIENT_ID = "VGFEeTkyV2QxV29ZQjhTVDIzRW86MTpjaQ"
const val CLIENT_SECRET = "M6IKSdp-UX1aSF7GCMn6hMlOsrdv6tHHFozKJW4nAh_b5SN4oY"
